[[redirects]]
  from = "/semesters/semester_:sem"
  to = "/notes/semester_:sem"
  status = 301

[[redirects]]
  from = "/semesters/subjects/semester_:sem_:subject"
  to = "/notes/semester_:sem/:subject"
  status = 301

[[redirects]]
  from = "/semesters/subjects/papers/:subject_:paper"
  to = "/notes/semester_1/:subject/:paper"
  status = 301

[[redirects]]
  from = "/semesters/subjects/papers/notes/:subject_:paper_unit_:unit"
  to = "/notes/semester_1/:subject/:paper/unit_:unit"
  status = 301
  force = true